---
steps:

  - wait

  - name: ":nodejs: Test It"
    command: docker-compose run --rm build bin/test
    agents:
      queue: native

  - wait

  - name: ":shipit: Ship It - Staging"
    command: docker-compose run --rm build bin/deploy $ENVIRONMENT
    branches: ec-build-pipeline
    env:
      ENVIRONMENT: staging
    agents:
      queue: native

  - manual

  - name: ":shipit: Ship It - Production"
    command: docker-compose run --rm build bin/deploy $ENVIRONMENT
    branches: ec-build-pipeline
    env:
      ENVIRONMENT: prod
    agents:
      queue: native
